### PR TITLE
Update to 2018

### PR DESCRIPTION
**Pull request by archer884**
I noticed some of these libraries are pretty old, and so I set out to update them (and, you know, migrate to the 2018 edition). In so doing, I also realized that the rustdct library kind of changed its API on you, apparently just to make life a little more fun. As such, my most important changes (read: the ones I understand the least) are in `dct_2d()`, on line 44 of `dct.rs`. The rest of this is pretty much 100% just me screwing with formatting and implementing advice from `cargo clippy`.

Anyway, here it is if you want it.

A note: at least after I did this, I did not notice any major difference in performance between dct and non-dct hashes (at least in [my tiny use case](https://github.com/archer884/pcom)). Of course, I didn't check to see what difference there was beforehand, and I don't know if the code even works correctly (although it seems to be producing valid hashes for me). There's no telling what, if anything, that indicates. That said, I did completely remove use of transpose from that code path. /shrug

### CODE REVIEW

**Comment by archer884** [comment]
I've been flipping back and forth between the version that I messed with and the original version and I don't really see any performance difference.

**Comment by stalkerg** [comment]
@abonander hey, looks like such a library is a little bit abandoned maybe we should make a fork?

**Comment by archer884** [comment]
I've got a fork of the repo with my updates in it that I've been using since I opened this PR, but I've never really thought of publishing it.

**Comment by stalkerg** [comment]
@archer884 you can check forks network and you can find many repositories with good improvements. Maybe you can consider publishing it and applying some extra things from other repositories? But I hope @abonander can a make comment on it.

**Pull request closed without merging**
